List<HymnData> responsive = [
HymnData(1, 'Invitation to Praise', [
'Make a joyful noise unto the Lord, all ye lands.','Serve the Lord with gladness: come before his presence with singing.','Know ye that the Lord he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.','Enter into his gates with thanksgiving, and into his courts with praise; be thankful unto him, and bless his name.','For the Lord is good; his mercy is everlasting; and his truth endureth to all generations.','Let the people praise thee, O God; let all the people praise thee.','O let the nations be glad and sing for joy: for thou shah judge the people righteously, and govern the nations upon earth.','Let the people praise thee, O God, let all the people praise thee.','Then shall the earth yield her increase; and God, even our own God, shall bless us.','God shall bless us; and all the ends of the earth shall fear him.'
]),
HymnData(2, 'Christian Fellowship', [
'Let love be without dissimulation, Abhor that which -is evil; cleave to that which is good.','Be kindly affectioned one to another with brotherly love; in honour preferring one another;','Distributing to the necessity of','saints; given to hospitality.','Rejoice with them that do rejoice, and weep with them that weep.','Be of the same mind one toward another. Mind .not high things,, but condescend to-meri^of low estate. Be not wise in your own conceits.','Recompense to no man evil for evil, Provide things honest in the sight of all men.','If it be possible as much as lieth in you, live peaceably with all men.','Bear ye one another\'s burdens, and so fulfil the law of Christ.','As we have therefore opportunity, let us do good unto all men, especially unto them who are of the household of faith.','Beloved, if God so loved us, we ought also to love one another.'
]),
HymnData(3, 'The Kingdom of God', [
'God, who at sundry times and in divers manners spake in time past unto the fathers by the prophets,','Hath in these last days spoken unto us by his Son, whom he hath appointed heir of all things, by whom also he made the worlds;','Unto the Son he saith, Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom.','Another parable spake, Jesus unto them; The kingdom of heaven is like unto leaven, which a woman took, and hid in three measures of meal, till the whole was leavened.','Again, the kingdom of heaven is like unto a merchant man, seeking goodly pearls;','Who, when he had found one pearl of great price, went and sold all that he had, and bought it.','Again, the kingdom of heaven is like unto a net, that was cast into the sea, and gathered of every kind:','Which, when it was full, they drew to shore, and sat down, and gathered the good into vessels, but cast (he bad away.','So shall it be at the end of the world: the angels shall come forth, and sever the wicked from among, the  just.','Then cometh the end, when Christ hall have delivered up the kingdom to God, even the Father; when he shall have put down all rule and all authority and power.','For fee must reign, till he hath put all enemies under his feet.','The kingdoms of this world are become the kingdoms of oar Lord and of his Christ; and be shall reign for ever and ever.'
]),
HymnData(4, 'True Greatness', [
'At the same time came the disciples unto Jesus, saying. Who is the greatest in the kingdom of heaven?','And Jer.is called a little child unto him, and set him \'in the midst of them,','And said, Verily I say unto you, Except ye be converted, and become as little children, ye shall not enter into the kingdom of heaven.','Whosoever therefore shall humble himself as this little child, the same is greatest in the kingdom of heaven.','Ye call me Master and Lord: and ye say well; for so I am.','If I then, your Lord and Master, have washed your feet; ye also ought to wash one another\'s feet.','For I have given you an example, that ye should do as I have done to you.','Verily, verily, I say unto you, The servant is not greater than his lord; neither he that is sent greater than he that sent him.','But whosoever will be great among you, shall be your minister: and whosoever of you will be the chiefest, shall be servant of all.','For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.'
]),
HymnData(5, 'God\'s World and World', [
'The heavens declare the glory of God; and the firmament showeth his handywork.','Day unto day uttereth speech, and night unto night showeth knowledge.','There is no speech nor language, where their voice is not heard.','Their line is gone out through all the earth, and their words to the end of the world.','In them hath he set a tabernacle for the sun, which is as a bridegroom coming out of his chamber, and re-joiceth as a strong man to run a race,','His going forth is from the end of the heaven, and his circuit unto the ends of it; and there is nothing hid from the heat thereof.','The law of the Lord is perfect, converting the soul:','The testimony of the Lord is sure, making wise the simple.','The statutes of the Lord are right, rejoicing the heart;','The commandment of the Lord is pure, enlightening the eyes.','The fear of the Lord is clean, enduring for ever:','The judgments of the Lord are true and righteous altogether,','More to be desired are they than gold, yea, than much fine gold:','Sweeter also than honey and the honeycomb','Moreover by them is thy servant armed; and in keeping of them there great reward.','Who can understand his errors? cleanse thou me from secret faults.','Keep back thy servant alto from presumptuous sins; let them not have dominion over me:','Let (the words of my mouth, and she meditation of my heart, be acceptable in thy sight, O Lord, my strength, and my redeemer.'
]),
HymnData(6, 'Peace Within', [
'Therefore being Justified by faith, we have peace With God through our Lord Jesus Christ:','For to be carnally minded is death; but to be spiritually minded is life and peace.','Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.','Trust ye in the Lord for ever: for in the Lord Jehovah is everlasting strength,','In everything by prayer and supplication with thanksgiving let your requests be made known unto God.','And the peace of God, which paas-eth all understanding, shall keep your hearts and minds through Christ Jesus.','Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant, make you perfect in every good work to do his will,','Working in you that which is well-pleasing in his sight, through Jesus Christ; to whom be glory for ever and ever. Amen.'
]),
HymnData(7, 'Good to Give Thanks', [
'It is a good thing to give thanks unto the Lord, and to sine praises unto thy name, O mmi High:','To show forth thy lovingkindness in the morning, and thy faithfulness every night.','Upon an instrument of ten strings, and upon the psaltery, upon the harp with a solemn sound,','For thou, Lord, hast made me glad through thy work: I will triumph in','the works of thy hands.','O Lord, how great are thy works!','and thy thoughts are very deep.','A brutish man knoweth not; neither doth a fool understand this.','When the wicked spring as the grass, and when all the workers of iniquity do flourish; it is that they shall be destroyed far ever:','But thou, Lord, art most high for evermore.','For, to, thine enemies, O Lord, for,','In, thine enemies shall perish;','All the workers of iniquity shall be','scattered.','The righteous shall flourish like','the palm tree: he shall grow like a','cedar in Lebanon,','Those that be planted in the of the Lord shall flourish in the courts of our God,','They shall bring forth fruit in old','To show that the Lord is upright: he is my rock, and there is no unrighteousness in him.'
]),
HymnData(8, 'God\'s Goodness', [
'Bless the Lord, O my soul; and ail that is within me, bless his holy name.','Bless the Lord, O my soul, and for','get not all his benefits;','Who forgiveth all thine iniquities;, who healeth all thy diseases;','Who redeemed thy life from destructions who crowneth thee with lovingkindness and tender mercies;','Who satisfied thy mouth with good things; so that thy youth is renewed like the eagle\'s,','The Lord executeth righteousness and judgment for all that are oppressed.','He made known his ways unto Moses, his arts unto the children of','Israel.','The Lord is merciful and gracious,','Slow to anger, and plenteous in mercy.','He will not always chide: neither will he keep his anger for ever.','He hath not dealt with us after our sins; nor rewarded us according to our iniquities.','For as the heaven is high above the earth, so great is his mercy toward them that fear him.','As far as the east is from the west, so far hath he removed our transgressions from us.','Like as a father pitieth his children, so the Lord pitieth them that fear him.','The mercy of the Lord is tram everlasting to everlasting upon them that fear him, and his righteousness unto children\'s children.'
]),
HymnData(9, 'The Commandments', [
'And God spake all these words, saying, I am the Lord thy God, Thou shah have no other gods before me.','Thou shall not make unto thee any graven image.','Thou shall not take the name of the Lord thy God in vain; for the Lord will not hold him guiltless that taketh his name in vain.','Remember the sabbath day, to keep it holy.','Honour thy father and thy mother: that thy days may be long upon the land which the Lord thy God giveth thee,','Thou shall not kill,','Thou shah not commit adultery,','Thou shah not steal.','Thou shah not bear false witness against thy neighbour.','Thou shall not covet anything that is thy neighbour\'s.','And one of the scribes came, and having heard them reasoning together, and perceiving that Jesus had answered them well, asked him, Which is the first commandment of all?','And Jesus answered him, The first of all the commandments is, Hear, O Israel; the Lord our God is one Lord;','And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy soul, and with all thy strength: this is the first commandment.','And the second is like, namely this, Thou shalt love thy neighbor as thy-','self. There is none other commandment greater than these.'
]),
HymnData(10, 'The Way of Wisdom', [
'Where shall wisdom be found? and where is the place of understanding?','Man knoweth not the price thereof; neither is it found in the land of the living,','It cannot begotten for gold, neither shall silver be weighed for the price thereof.','Whence then cometh wisdom? and where is the place of understanding?','God understandeth the way thereof. and he knoweth the place thereof.','And unto man he said, Behold, she fear of the Lord, that is wisdom; and to depart from evil is understanding.','Happy is the man that findeth wisdom, and the man that getteth understanding.','For the merchandise of it is better than the merchandise of silver, and the gain thereof than fine gold.','She is more precious than rubies: and all the things thou cam! desire are not to be compared unto her,','Length of days is in her right hand; and in her left hand riches and honour.','Her ways arc ways of pleasantness, and all her paths are peace,','If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.'
]),
HymnData(11, 'A Sinner\'s Confession', [
'Have mercy upon me, O God, according to thy lovingkindness:','According unto the multitude of thy tender mercies blot out my trans-','Wash me thoroughly from mine iniquity, and cleanse me from my sin,','For I acknowledge my transgressions; and my sin is ever before me.','Against thee, thee only, have I sinned, and done this evil in thy sight:','That thou mightest be justified when thou speakest, and be clear when thou judges t.','Behold, I was shapen in iniquity; and in sin did my mother conceive me,','Behold, thou desirest truth in the inward parts: and in the hidden part thou shalt make me to know wisdom.','Purge me with hyssop, and I shall be clean; wash me, and I shall be whiter than snow,','Make me to hear joy and gladness; that the bones which thou hast broken may rejoice.','Hide thy face from -my sins, and Wot out all mine iniquities,','Create in me a clean heart, O God; and renew a right spirit within the.','Cast me not away from thy presence; and take not thy holy spirit from me,','Restore unto me the joy of thy salvation; and uphold me with thy free spirit,','Then will I teach transgressors thy ways; and sinners shall be convened unto thee,','The sacrifices of God are a broken spirit; a broken and a contrite heart, O God, thou wilt not despise.'
]),
HymnData(12, 'God Ever Present', [
'O Lord, thou hast searched me, an> known me.','Thou compasses t my path and my lying down, and art acquainted with','all my ways.','Whither shall I go from thy spirit? or whither shall I flee from thy presence?','If I ascend up into heaven, thou art there.','If I take the wings of the morning, and dwell in the uttermost parts of the sea;','Even there shall thy hand lead me, and thy right hand shall hold me.','If I say, Surely the darkness shall cover me; even the night shall be light about me.','Yea, the darkness hideth not from thee; bat the night shineth as the day; the darkness and the light are both alike to thee,','I will praise thee; for I am fearfully and wonderfully made; marvellous are thy works; and that my soul knoweth right well,','How precious also are thy thoughts unto me, O God! how great is the sum of them!','Search me, O God, and know my heart; try me, and know my thoughts:','See if there be any wicked way in me, and lead me in the way everlasting.'
]),
HymnData(13, 'Acceptable Worship', [
'The earth is the Lord\'s, and the fulness thereof; the world, and they that dwell therein.','For he hath founded it upon the seas, and established it upon the floods.','Who shall ascend into the hill of the Lord? or who shall stand in his holy place?','He that hath clean hands, and a pure heart; who hath not lifted up his soul unto vanity, nor sworn deceitfully.','He shall receive the blessing from the Lord, and righteousness from the God of his salvation,','Lift up your heads, O ye gates; and be ye lift up, ye everlasting doors, and the King of glory shall come in.','Who is this King of glory?','The Lord strong and mighty, the Lord mighty in battle.','Lift up your heads, O ye gates; even lift them up, ye everlasting doors; and the King of glory shall come in.','Who Is this King of glory?','The Lord of hosts, he is the King of glory,','But the hour cometh, and now is, when the true worshippers shall worship the Father in spirit and in truth: for the Father seeketh such to worship him.','God is a Spirit: and they that worship him roust worship him in spirit and in truth.'
]),
HymnData(14, 'Dignity of Man', [
'O Lord our Lord, how excellent is thy name in all the earth! Who hast set thy glory above the heavens.','Out of the mouth of babes and sucklings hast thous ordained strength because of thine enemies','When I consider thy heavens, the work of thy fingrers, the moon and the stars, which thou hast ordained;','What is man, that thou art mindful of him? and the son of man, that thou visitest him?','For thou hast made him a little lower than the angels, and hast crowned him with glory and honour,','Thou madest him to have dominion over the works of thy hands;','Thou hast put all things under his feet: all sheep and oxen, yea, and the beasts of the field;','The fowl of the air, and the fish of the sea, and whatsoever passeth through the paths of the seas.','O Lord our Lord, how excellent is','thy name in all the earth!','Behold, what manner of Jove the Father hath bestowed upon us, that we should be called the son of Cod.','Beloved, now are we the sons of God, and it doth not yet appear what we shall be;','But we know that, when he shall appear, we shall be like him;','For we shall see him as he is.','And every man that hath this hope in him purtfieth himself, even as he is pure.'
]),
HymnData(15, 'The Lord Our Shepherd', [
'The Lord is my shepherd; I shall not want,','He maketh me to lie clown in green pastures: he leadeth me beside the still waters,','He restoreth my soul: he leadeth me in the paths of righteousness for his name\'s sake.','Yea, though I walk through the valley of the shadow of death, I will fear','no evil for thou art with me; thy rod and thy staff they comfort me.','Thou preparest a table before me in the presence of mine enemies; thou anointest my head with oil; my cup runneth over.','Surely goodness and mercy shall follow me all the days of my life: and I Kill dwell in the house of the Lord forever,'
]),
HymnData(16, 'Jesus Our Friend', [
'Then drew near unto Jesus al! the publicans and sinners to hear him,','And the Pharisees and scribes murmured, saying, This man receiveth sinners, and eateth with them.','And Jesus answering said unto them, They that are whole need not a physician; but they that are sick.','I came not to call the righteous, but sinners to repentance.','And him that cometh to me I will','in no wise cast out','Ye have not chosen roe, but I have chosen you.','As the Father hath loved me, $o have I loved you: continue ye in my love,','Greater love hath no man than this, that a man lay down his life for his','friends.','Ye are my friends, if ye do whatsoever I command you.','Henceforth I call you not servants; for the servant knowcth not what his lord docth: _ but I have called you','friends," for all things chat I have heard of my Falter I have mad known unto you.'
]),
HymnData(17, 'Patience', [
'I had fainted, unless I had believed','to see the goodness of the Lord in the land of the living.','Wait on the Lord: be of good courage, and he shall strengthen thine heart: wait I say, on the Lord','My brethren, count it all joy when ye fall into divers temptations;','Knowing this, that the trying of your faith worketh patience,','But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.','We glory in tribulations also: knowing that tribulation worketh patience;','And patience, experience; and experience, hope:','And hope maketh not ashamed; because the love of God is shed abroad in our heart by the Holy Spirit which b given unto us.','Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath Jong patience for it, until he receive the early and fatter rain,','Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh.'
]),
HymnData(18, 'God\'s Word', [
'Blessed art thou, O Lord: teach me thy statutes.','Thy word have I hid in mine heart, that I might not tin against thee.','I have rejoiced in the way of thy testimonies, as much m in all riches.','I will meditate in thy precepts, and have respect unto thy ways.','I will delight myself in thy statutes: I will not forget thy word.','Thy hands have made me and fashioned me; give me understanding, that I may, learn thy commandments.','Thy word is a lamp unto my feet, and a light unto my path,','Thy testimonies have I taken as an heritage forever; for they are the rejoicing of my heart.','All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness;','That the man of God may be perfect thoroughly furnished unto all good works.'
]),
HymnData(19, 'Sanctification', [
'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temper ance: against such there is no law,','And they that are Christ\'s have crucified the flesh with the affections and lusts.','If we live in the Spirit, let us also walk in the Spirit.','Therefore, brethren, we are debtor, not to the flash, to live after the flesh,','For if ye live after the flesh, ye shall disc: bat if ye through the Spirit da mortify the deeds of the body, ye shall','Live.','For as many as are led by the Spirit of God, they are the sons of God.','Let not sin therefore reign in your mortal body, that ye should obey it in the lusts thereof.','Neither yield ye your members as instruments of unrighteousness unto','sin:','But yield yourselves unto God, as those that are alive from the dead, and your members as instruments of righteousness unto Cod,','For sin shall not have dominion over you: for ye are not under law, but under grace.'
]),
];